name: bump CSS only

on:
  workflow_dispatch: {}        # lets you run manually
  schedule:
    - cron: "*/10 * * * *"     # auto every 10 min

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: rewrite theme.css with fresh ?v=
        shell: bash
        run: |
          set -euo pipefail
          STAMP=$(date +%s)
          cat > theme.css <<EOF
/* theme.css — generated */
.content_a2f514::before{
  content:"";
  display:block;
  width:256px;
  height:256px;
  margin:0 auto 160px;
  background-image:url("https://cdn.jsdelivr.net/gh/gifstorage/gifstorage1@main/random.gif?v=$STAMP");
  background-repeat:no-repeat;
  background-position:center;
  background-size:contain;
  image-rendering:pixelated;
}
EOF
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add theme.css
          git commit -m "bump theme.css v=$STAMP" || echo "no change"
          git push origin HEAD:main || true
