name: rotate random.gif

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: pick gif, update random.gif and write theme.css
        shell: bash
        run: |
          set -euo pipefail
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          shopt -s nullglob nocaseglob

          # gather candidates (exclude random.gif)
          candidates=()
          for f in ./*.gif; do
            [[ "$(basename "$f")" == "random.gif" ]] && continue
            candidates+=( "$f" )
          done
          if [[ ${#candidates[@]} -eq 0 ]]; then
            echo "no candidate gifs found"; exit 1
          fi

          pick="${candidates[$(( RANDOM % ${#candidates[@]} ))]}"
          echo "picked: $(basename "$pick")"

          # update random.gif if different
          [[ -f random.gif ]] || cp -f "$pick" random.gif
          if ! cmp -s "$pick" random.gif; then
            cp -f "$pick" random.gif
          fi

          # always rewrite theme.css with fresh cache-buster
          STAMP=$(date +%s)
          cat > theme.css <<EOF
/* theme.css — generated */
.content_a2f514::before{
  content:"";
  display:block;
  width:256px;
  height:256px;
  margin:0 auto 160px;
  background-image:url("https://cdn.jsdelivr.net/gh/gifstorage/gifstorage1@main/random.gif?v=$STAMP");
  background-repeat:no-repeat;
  background-position:center;
  background-size:contain;
  image-rendering:pixelated;
}
EOF

          # commit once (both files) and push to main explicitly
          git add random.gif theme.css || true
          if ! git diff --cached --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "rotate $(basename "$pick"); theme.css v=$STAMP"
            git push origin HEAD:main
          else
            echo "nothing to commit"
          fi

      - name: purge jsdelivr (gif + css) and warm
        shell: bash
        run: |
          set +e
          curl -sS "https://purge.jsdelivr.net/gh/gifstorage/gifstorage1@main/random.gif" >/dev/null
          curl -sS "https://purge.jsdelivr.net/gh/gifstorage/gifstorage1@main/theme.css"  >/dev/null
          curl -sI "https://cdn.jsdelivr.net/gh/gifstorage/gifstorage1@main/theme.css"    >/dev/null
          curl -sI "https://cdn.jsdelivr.net/gh/gifstorage/gifstorage1@main/random.gif"   >/dev/null
          exit 0
