name: rotate random.gif

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: pick random gif and update random.gif
        shell: bash
        run: |
          set -euo pipefail
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          shopt -s nullglob nocaseglob
          files=( ./*.gif )
          # remove random.gif from candidates
          tmp=()
          for f in "${files[@]}"; do
            [[ "$(basename "$f")" == "random.gif" ]] || tmp+=( "$f" )
          done
          files=( "${tmp[@]}" )
          if [[ ${#files[@]} -eq 0 ]]; then
            echo "no candidate gifs"; exit 1
          fi
          pick="${files[$(( RANDOM % ${#files[@]} ))]}"
          echo "picked: $pick"
          [[ -f random.gif ]] || cp -f "$pick" random.gif
          if ! cmp -s "$pick" random.gif; then
            cp -f "$pick" random.gif
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add random.gif
            git commit -m "rotate random.gif -> $(basename "$pick")"
            git push
          else
            echo "random.gif unchanged; skipping commit"
          fi

      - name: bump CSS cache-buster
        shell: bash
        run: |
          set -e
          stamp=$(date +%s)
          css_file="theme.css"
          if [[ -f "$css_file" ]]; then
            # replace any existing ?v=... with the new stamp
            sed -i.bak -E 's|(random\.gif\?v=)[0-9A-Za-z_-]+|\1'"$stamp"'|g' "$css_file" || true
            rm -f "$css_file.bak"
          else
            cat > "$css_file" <<EOF
.content_a2f514::before{
  content:"";
  display:block;
  width:256px;
  height:256px;
  margin:0 auto 160px;
  background-image:url("https://cdn.jsdelivr.net/gh/gifstorage/gifstorage1@main/random.gif?v=$stamp");
  background-repeat:no-repeat;
  background-position:center;
  background-size:contain;
  image-rendering:pixelated;
}
EOF
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add theme.css
          git commit -m "bump theme.css cache-buster -> v=$stamp" || echo "no css change"
          git push || true

      - name: purge jsDelivr (gif + css) and warm
        shell: bash
        run: |
          set -e
          PURGE1="https://purge.jsdelivr.net/gh/gifstorage/gifstorage1@main/random.gif"
          PURGE2="https://purge.jsdelivr.net/gh/gifstorage/gifstorage1@main/theme.css"
          echo "Purging..."
          curl -sS "$PURGE1" >/dev/null
          curl -sS "$PURGE2" >/dev/null
          echo "Warming..."
          curl -sI "https://cdn.jsdelivr.net/gh/gifstorage/gifstorage1@main/theme.css" >/dev/null || true
          curl -sI "https://cdn.jsdelivr.net/gh/gifstorage/gifstorage1@main/random.gif" >/dev/null || true
