name: rotate random.gif

on:
  schedule:
    - cron: "*/10 * * * *"     # auto
  workflow_dispatch: {}         # manual Run workflow button

permissions:
  contents: write

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: pick random gif and update random.gif
        shell: bash
        run: |
          set -euo pipefail
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          shopt -s nullglob nocaseglob
          files=( ./*.gif )
          # exclude random.gif
          candidates=()
          for f in "${files[@]}"; do
            [[ "$(basename "$f")" == "random.gif" ]] || candidates+=( "$f" )
          done
          if [[ ${#candidates[@]} -eq 0 ]]; then
            echo "no candidate gifs"; exit 1
          fi
          pick="${candidates[$(( RANDOM % ${#candidates[@]} ))]}"
          echo "picked: $(basename "$pick")"
          [[ -f random.gif ]] || cp -f "$pick" random.gif
          if ! cmp -s "$pick" random.gif; then
            cp -f "$pick" random.gif
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add random.gif
            git commit -m "rotate random.gif -> $(basename "$pick")"
            git push
          else
            echo "random.gif unchanged; skipping commit"
          fi

      - name: write theme.css with new cache-buster
        shell: bash
        run: |
          set -e
          STAMP=$(date +%s)
          cat > theme.css <<EOF
/* theme.css — generated */
.content_a2f514::before{
  content:"";
  display:block;
  width:256px;
  height:256px;
  margin:0 auto 160px;
  background-image:url("https://cdn.jsdelivr.net/gh/gifstorage/gifstorage1@main/random.gif?v=$STAMP");
  background-repeat:no-repeat;
  background-position:center;
  background-size:contain;
  image-rendering:pixelated;
}
EOF
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add theme.css
          git commit -m "bump theme.css cache-buster -> v=$STAMP"
          git push

      - name: purge jsDelivr (gif + css) and warm
        shell: bash
        run: |
          set -e
          curl -sS "https://purge.jsdelivr.net/gh/gifstorage/gifstorage1@main/random.gif" >/dev/null
          curl -sS "https://purge.jsdelivr.net/gh/gifstorage/gifstorage1@main/theme.css"  >/dev/null
          # warm (helps some clients fetch fresh)
          curl -sI "https://cdn.jsdelivr.net/gh/gifstorage/gifstorage1@main/theme.css" >/dev/null || true
